export const keywords: Record<string, string[]> = {
  python: ["python", "data-science", "analytics", "machine-learning"],
  pandas: ["data-science", "analytics"],
  numpy: ["data-science", "analytics"],
  sql: ["databases", "analysis", "data-engineering"],
  nosql: ["databases", "data-engineering"],
  spark: ["data-engineering", "pipelines"],
  airflow: ["pipelines", "automation"],
  dbt: ["pipelines", "governance"],
  javascript: ["frontend", "web", "coding"],
  typescript: ["typescript", "frontend", "ui-architecture"],
  react: ["frontend", "design-systems", "ui-architecture"],
  next: ["frontend", "performance", "ui-architecture"],
  redux: ["state-management", "frontend"],
  tailwind: ["design-systems", "frontend"],
  accessibility: ["accessibility", "frontend"],
  performance: ["performance", "optimization"],
  a11y: ["accessibility", "frontend"],
  node: ["backend", "apis", "coding"],
  express: ["backend", "api-design"],
  graphql: ["apis", "product-thinking"],
  rest: ["apis", "backend"],
  docker: ["devops", "automation", "infrastructure"],
  kubernetes: ["devops", "cloud", "automation"],
  terraform: ["infrastructure", "automation", "cloud"],
  ci: ["ci-cd", "automation"],
  cd: ["ci-cd", "automation"],
  observability: ["observability", "devops"],
  monitoring: ["monitoring", "observability", "risk"],
  logging: ["observability", "backend"],
  tracing: ["observability", "distributed-systems"],
  postgres: ["databases", "backend"],
  mysql: ["databases", "backend"],
  mongodb: ["databases", "backend"],
  redis: ["databases", "performance"],
  microservices: ["distributed-systems", "backend"],
  event: ["distributed-systems", "pipelines"],
  message: ["distributed-systems", "pipelines"],
  queue: ["distributed-systems", "pipelines"],
  security: ["security", "risk", "governance"],
  threat: ["threat-modeling", "security"],
  incident: ["incident-response", "risk"],
  forensics: ["security", "incident-response"],
  governance: ["governance", "security"],
  compliance: ["governance", "risk"],
  aws: ["cloud", "infrastructure"],
  azure: ["cloud", "infrastructure"],
  gcp: ["cloud", "infrastructure"],
  serverless: ["cloud", "cost-optimization"],
  finops: ["cost-optimization", "cloud"],
  mlops: ["ml-ops", "automation"],
  ml: ["machine-learning", "ml-engineering"],
  pytorch: ["machine-learning", "ml-engineering"],
  tensorflow: ["machine-learning", "ml-engineering"],
  model: ["machine-learning", "ml-engineering"],
  pipeline: ["pipelines", "automation"],
  experimentation: ["analysis", "product"],
  analytics: ["analytics", "analysis"],
  statistics: ["statistics", "analysis"],
  storytelling: ["storytelling", "communication"],
  stakeholder: ["stakeholder", "communication"],
  roadmap: ["roadmap", "strategy"],
  strategy: ["strategy", "product"],
  product: ["product", "product-thinking"],
  discovery: ["product", "ux-research"],
  prioritization: ["roadmap", "program-execution"],
  ux: ["design", "ux-research"],
  research: ["ux-research", "analysis"],
  prototype: ["interaction", "design"],
  wireframe: ["design", "interaction"],
  figma: ["design", "design-systems", "ux-research"],
  motion: ["creativity", "design"],
  mentorship: ["mentorship", "leadership"],
  leadership: ["leadership", "communication"],
  collaboration: ["collaboration", "stakeholder"],
  marketing: ["marketing", "content"],
  seo: ["seo", "marketing"],
  content: ["content", "storytelling"],
  program: ["program-execution", "tpm"],
  risk: ["risk", "risk-management"],
  execution: ["program-execution", "strategy"],
  automation: ["automation", "devops"],
  testing: ["testing", "quality"],
  quality: ["testing", "analysis"],
  resilience: ["risk", "distributed-systems"],
  scalability: ["scalability", "distributed-systems"],
  resiliency: ["risk", "distributed-systems"],
  monitor: ["monitoring", "observability"],
  telemetry: ["observability", "analytics"],
  coaching: ["mentorship", "leadership"],
  facilitation: ["communication", "stakeholder"],
  innovation: ["creativity", "strategy"],
  vision: ["strategy", "communication"],
};

export default keywords;
